GET http://localhost:4000/user/getAllUsersfasgas

###

POST http://localhost:4000/user/register
Content-Type: application/json

{
  "username": "daoquang",
  "password": "123456"
}


###

POST http://localhost:4000/user/login
Content-Type: application/json

{
  "username": "Antonette",
  "password": "123456"
}

###
GET http://localhost:4000/film/getAllFilms

###
GET http://localhost:4000/film/getFilmDetail?id=79
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFudG9uZXR0ZSIsImlkIjoyLCJpYXQiOjE2ODMyMjE1NTZ9.TQBlIkwQ75avueTQGrHvM1S3kobYalXTpsWjambzKAA